"""users: phone required unique login id, email optional; otp_codes: phone replaces email

Revision ID: 6b1517b587a9
Revises: 4699265d6ed2
Create Date: 2026-07-13 07:37:52.476262

Note: otp_codes rows are ephemeral (10-min expiry, single-use), so rather
than backfill a value for the new NOT NULL `phone` column, this migration
truncates the table first. Any in-flight OTP request at deploy time is
simply invalidated - the user requests a new code.

Note: users.phone is set NOT NULL on the assumption the users table has
no rows yet (pre-launch). Before running this against a live database,
confirm with `SELECT COUNT(*) FROM users;` that this still holds.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b1517b587a9'
down_revision = '4699265d6ed2'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("DELETE FROM otp_codes")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=False))
        batch_op.drop_index(batch_op.f('ix_otp_codes_email'))
        batch_op.create_index(batch_op.f('ix_otp_codes_phone'), ['phone'], unique=False)
        batch_op.drop_column('email')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_index(batch_op.f('ix_otp_codes_phone'))
        batch_op.create_index(batch_op.f('ix_otp_codes_email'), ['email'], unique=False)
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
